export const initialState = {
  deckId: "",
  dealerFaceCards: [],
  dealerHidden: [],
  playerCards: [],
  splitOnceCards: [],
  splitTwiceCards: [],
  splitThreeCards: [],
  playerCardTotals: 0,
  playerTotal: 0,
  dealerTotal: 0,
  playerBlackjack: false,
  dealerBlackjack: false,
  double: false,
  stand: false,
  dealerEndGo: false,
};
