export const deck = [
  { value: "ACE", suit: "HEART", image: "AH" },
  { value: "ACE", suit: "HEART", image: "AH" },
  { value: "ACE", suit: "HEART", image: "AH" },
  { value: "ACE", suit: "HEART", image: "AH" },
  { value: "ACE", suit: "HEART", image: "AH" },
  { value: 10, suit: "HEART", image: "KH" },
  { value: 10, suit: "HEART", image: "QH" },
  { value: 10, suit: "HEART", image: "JH" },
  { value: 10, suit: "HEART", image: "10H" },
  // { value: 9, suit: "HEART", image: "9H" },
  // { value: 8, suit: "HEART", image: "8H" },
  // { value: 7, suit: "HEART", image: "7H" },
  // { value: 6, suit: "HEART", image: "6H" },
  // { value: 5, suit: "HEART", image: "5H" },
  // { value: 4, suit: "HEART", image: "4H" },
  // { value: 3, suit: "HEART", image: "3H" },
  // { value: 2, suit: "HEART", image: "2H" },
  { value: "ACE", suit: "CLUB", image: "AC" },
  { value: 10, suit: "CLUB", image: "KC" },
  { value: 10, suit: "CLUB", image: "QC" },
  { value: 10, suit: "CLUB", image: "JC" },
  { value: 10, suit: "CLUB", image: "10C" },
  // { value: 9, suit: "CLUB", image: "9C" },
  // { value: 8, suit: "CLUB", image: "8C" },
  // { value: 7, suit: "CLUB", image: "7C" },
  // { value: 6, suit: "CLUB", image: "6C" },
  // { value: 5, suit: "CLUB", image: "5C" },
  // { value: 4, suit: "CLUB", image: "4C" },
  // { value: 3, suit: "CLUB", image: "3C" },
  // { value: 2, suit: "CLUB", image: "2C" },
  { value: "ACE", suit: "DIAMOND", image: "AD" },
  { value: 10, suit: "DIAMOND", image: "KD" },
  { value: 10, suit: "DIAMOND", image: "QD" },
  { value: 10, suit: "DIAMOND", image: "JD" },
  { value: 10, suit: "DIAMOND", image: "10D" },
  // { value: 9, suit: "DIAMOND", image: "9D" },
  // { value: 8, suit: "DIAMOND", image: "8D" },
  // { value: 7, suit: "DIAMOND", image: "7D" },
  // { value: 6, suit: "DIAMOND", image: "6D" },
  // { value: 5, suit: "DIAMOND", image: "5D" },
  // { value: 4, suit: "DIAMOND", image: "4D" },
  // { value: 3, suit: "DIAMOND", image: "3D" },
  // { value: 2, suit: "DIAMOND", image: "2D" },
  { value: "ACE", suit: "SPADE", image: "AS" },
  { value: 10, suit: "SPADE", image: "KS" },
  { value: 10, suit: "SPADE", image: "QS" },
  { value: 10, suit: "SPADE", image: "JS" },
  { value: 10, suit: "SPADE", image: "10S" },
  // { value: 9, suit: "SPADE", image: "9S" },
  // { value: 8, suit: "SPADE", image: "8S" },
  // { value: 7, suit: "SPADE", image: "7S" },
  // { value: 6, suit: "SPADE", image: "6S" },
  // { value: 5, suit: "SPADE", image: "5S" },
  // { value: 4, suit: "SPADE", image: "4S" },
  // { value: 3, suit: "SPADE", image: "3S" },
  // { value: 2, suit: "SPADE", image: "2S" },
].map((card) => Object.freeze(card));
